version: "3"
services:
  nodeapi:
    container_name: "nodejs"
    image: "node:latest"
    restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes: 
      - ./:/home/node/app
    ports:
      - "3001:3000"
    command: "npm run dev"
    deploy:
      restart_policy:
        condition: any
        delay: 5s


  #MongoDB
  mongoapi:
    container_name: mongoapi
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - "27017:27017"
    volumes:
      - ${PWD}/mongodb:/data/db
    depends_on:
      - nodeapi
    deploy:
      restart_policy:
        condition: any
        delay: 5s
